# fly.toml app configuration file generated for think-storm-frontend on 2024-06-17T20:57:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ts-frontend'
primary_region = 'cdg'

[[services]]
  internal_port = 3000  # Port privé interne sur lequel le backend écoute
  protocol = "tcp"

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "10s"
    retries = 3
    port = 3000  # Vérification de santé sur le port interne du backend

  [[services.ports]]
  handlers = ["http"]
  port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
