name: Pre Integration Verification Pipeline

permissions:
  contents: read
  packages: read
  id-token: write # Required for requesting the JWT

on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:
jobs:
  pre-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          contract-access-token: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        uses: ./.github/actions/lint

      - name: Build
        uses: ./.github/actions/build
        with:
          build-args: '--build-arg CONTRACT_ACCESS_TOKEN=${{ secrets.NPM_TOKEN }}'
          env-variables: 'NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}'
