name: Push Verification Pipeline

permissions:
  contents: read # for actions/checkout
  packages: read # for GitHub Packages
  id-token: write # Required for requesting the JWT

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  push-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          contract-access-token: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        uses: ./.github/actions/lint

      - name: Build
        uses: ./.github/actions/build
        with:
          build-args: '--build-arg CONTRACT_ACCESS_TOKEN=${{ secrets.NPM_TOKEN }}'
